version: '3.8'

services:
  api:
    build:
      context: https://github.com/rastamansp/gwan-python-app.git
      dockerfile: Dockerfile
    container_name: gwan_python_api
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://gwan_user:gwan_password@db:5432/gwan_db
      - DEBUG=False
      - RABBITMQ_HOST=rabbitmq.gwan.com.br
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=pazdeDeus2025
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - gwan
    labels:
      - "traefik.enable=true"
      # Configuração HTTPS
      - "traefik.http.routers.gwan-python.rule=Host(`api.gwan.com.br`)"
      - "traefik.http.routers.gwan-python.entrypoints=websecure"
      - "traefik.http.routers.gwan-python.tls=true"
      - "traefik.http.routers.gwan-python.tls.certresolver=letsencrypt"
      # Configuração do serviço
      - "traefik.http.services.gwan-python.loadbalancer.server.port=8000"

  knowledge_worker:
    build:
      context: https://github.com/rastamansp/gwan-python-app.git
      dockerfile: Dockerfile
    container_name: gwan_python_knowledge_worker
    restart: always
    command: python -m src.workers.knowledge_worker
    environment:
      - DATABASE_URL=postgresql://gwan_user:gwan_password@db:5432/gwan_db
      - DEBUG=False
      - RABBITMQ_HOST=rabbitmq.gwan.com.br
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=pazdeDeus2025
      - MONGODB_URI=mongodb://mongodb.gwan.com.br:27017
      - MONGODB_DB=gwan
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - gwan

  worker:
    build:
      context: https://github.com/rastamansp/gwan-python-app.git
      dockerfile: Dockerfile
    container_name: gwan_python_worker
    restart: always
    command: python -m src.workers.pdf_worker
    environment:
      - DATABASE_URL=postgresql://gwan_user:gwan_password@db:5432/gwan_db
      - DEBUG=False
      - RABBITMQ_HOST=rabbitmq.gwan.com.br
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=pazdeDeus2025
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - gwan

  db:
    image: postgres:15-alpine
    container_name: gwan_python_db
    restart: always
    environment:
      - POSTGRES_USER=gwan_user
      - POSTGRES_PASSWORD=gwan_password
      - POSTGRES_DB=gwan_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gwan

volumes:
  postgres_data:


networks:
  gwan:
    external: true
