"""add document embeddings table

Revision ID: f3daa7256320
Revises: 
Create Date: 2025-06-06 20:01:43.605588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3daa7256320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.String(), nullable=False, name='knowledge_base_id'),
    sa.Column('user_id', sa.String(), nullable=False, name='user_id'),
    sa.Column('bucket_file_id', sa.String(), nullable=False, name='bucket_file_id'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, name='chunk_index'),
    sa.Column('content', sa.Text(), nullable=False, name='content'),
    sa.Column('embedding', sa.Text(), nullable=False, name='embedding'),
    sa.Column('meta', sa.JSON(), nullable=True, name='meta'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embeddings_bucket_file_id'), 'document_embeddings', ['bucket_file_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_id'), 'document_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_knowledge_base_id'), 'document_embeddings', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_user_id'), 'document_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_embeddings_user_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_knowledge_base_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_bucket_file_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    # ### end Alembic commands ### 